(() => {
  const URL=window.METROCITY_SUPABASE_URL,KEY=window.METROCITY_SUPABASE_KEY,API=`${URL}/rest/v1`;
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const safeUrl=v=>{try{const u=new URL(v,location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const get=async path=>{const r=await fetch(API+path,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`},cache:'no-store'});if(!r.ok)throw new Error(`Supabase ${r.status}`);return r.json()};
  const dateKey=v=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return '';return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};
  const dateLabel=v=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return '';return new Intl.DateTimeFormat('mr-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'long',year:'numeric'}).format(d)};
  const timeLabel=v=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return '';return new Intl.DateTimeFormat('mr-IN',{timeZone:'Asia/Kolkata',hour:'numeric',minute:'2-digit',hour12:true}).format(d)};
  const shortText=(v,n=160)=>{const s=String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s};
  const slugLink=slug=>`news.html?slug=${encodeURIComponent(slug||'')}`;
  function groupEpapers(rows){const map=new Map();[...(rows||[])].sort((a,b)=>new Date(b.published_at||b.created_at)-new Date(a.published_at||a.created_at)).forEach(row=>{const key=dateKey(row.published_at||row.created_at);if(!key)return;if(!map.has(key))map.set(key,{type:'epaper',dateKey:key,items:[],latestAt:row.published_at||row.created_at,first:row});map.get(key).items.push(row)});return [...map.values()]}
  function unified(epapers,written){return [...epapers.map(g=>({...g,sortAt:g.latestAt})),...written.map(row=>({type:'written',sortAt:row.published_at||row.created_at,row}))].sort((a,b)=>new Date(b.sortAt)-new Date(a.sortAt))}
  function writtenCard(n){const img=safeUrl(n.main_image_url),href=slugLink(n.slug);return `<article class="home-story"><a href="${esc(href)}" class="written-card-link"><span class="home-story-media ${img?'':'no-image'}">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:'📝'}</span><span class="home-story-body"><span class="story-meta"><span class="tag">${esc(n.category_name||'बातमी')}</span><span class="story-time">${esc(timeLabel(n.published_at||n.created_at))}</span></span><h3>${esc(n.headline||'बातमी')}</h3><p>${esc(shortText(n.subheadline||n.content||'',120))}</p><span class="read-more">बातमी वाचा <span>→</span></span></span></a></article>`}
  function renderWritten(items){const box=$('#written-list');if(!box)return;if(!items.length){box.innerHTML='<div class="empty written-empty">अजून लिखित बातम्या प्रकाशित झालेल्या नाहीत.</div>';return}box.innerHTML=items.slice(0,8).map(writtenCard).join('')}
  function writtenLatest(item){const n=item.row,img=safeUrl(n.main_image_url),href=slugLink(n.slug);return `<article class="latest-written"><a class="latest-visual" href="${esc(href)}">${img?`<img src="${esc(img)}" alt="${esc(n.headline||'बातमी')}" fetchpriority="high">`:'📝'}<span class="latest-type">📝 लिखित बातमी</span></a><div class="latest-copy"><span class="section-kicker">${esc(n.category_name||'ताजी बातमी')}</span><h2>${esc(n.headline||'ताजी बातमी')}</h2><p>${esc(shortText(n.subheadline||n.content||'',220))}</p><div class="meta-line">प्रकाशित ${esc(dateLabel(n.published_at||n.created_at))} • ${esc(timeLabel(n.published_at||n.created_at))}</div><a class="latest-action" href="${esc(href)}">संपूर्ण बातमी वाचा →</a></div></article>`}
  function renderLatest(item){const box=$('#latest-content'),ep=$('#epaper-section'),latest=$('#latest'),written=$('#written');if(!box)return;if(!item){box.innerHTML='<div class="empty">अजून कोणतेही प्रकाशित कंटेंट उपलब्ध नाही.</div>';return}if(item.type==='epaper'){box.innerHTML='<div class="latest-reader-note"><span class="type-badge">सर्वात नवीन • ई-पेपर</span><strong>आजचा अंक थेट येथे वाचा</strong><span>पानांमध्ये पुढे-मागे जा, झूम करा किंवा पूर्ण स्क्रीन वापरा.</span></div>';if(ep&&latest)latest.insertAdjacentElement('afterend',ep);$('#epaper-section-status').textContent='सध्या सर्वात नवीन'}else{box.innerHTML=writtenLatest(item);if(ep&&written)written.insertAdjacentElement('afterend',ep);$('#epaper-section-status').textContent='दैनिक अंक'}}

  document.addEventListener('DOMContentLoaded',init);
})();
