(() => {
  const URL = window.METROCITY_SUPABASE_URL, KEY = window.METROCITY_SUPABASE_KEY, API = `${URL}/rest/v1`;
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const safeUrl=v=>{try{const u=new URL(v,location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
  const get=async path=>{const r=await fetch(API+path,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`},cache:'no-store'});if(!r.ok)throw new Error(`Supabase ${r.status}`);return r.json()};
  const stamp=v=>{const n=new Date(v||0).getTime();return Number.isFinite(n)?n:0};
  const time=v=>new Intl.DateTimeFormat('mr-IN',{timeZone:'Asia/Kolkata',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(v));
  const date=v=>new Intl.DateTimeFormat('mr-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'long',year:'numeric'}).format(new Date(v));
  const dateKey=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
  const text=(v,n=170)=>{const s=String(v||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s};
  const normalize=r=>({...r,category_name:r.categories&&typeof r.categories==='object'?r.categories.name:''});
  const groupEpapers=rows=>{const map=new Map();[...(rows||[])].sort((a,b)=>stamp(b.published_at||b.created_at)-stamp(a.published_at||a.created_at)).forEach(r=>{const k=dateKey(r.published_at||r.created_at);if(!map.has(k))map.set(k,{type:'epaper',dateKey:k,items:[],latestAt:r.published_at||r.created_at});map.get(k).items.push(r)});return [...map.values()]};
  const unified=(groups,written)=>[...groups.map(g=>({type:'epaper',sortAt:g.latestAt,group:g})),...written.map(r=>({type:'written',sortAt:r.published_at||r.created_at,row:r}))].sort((a,b)=>stamp(b.sortAt)-stamp(a.sortAt));
  const link=r=>`news.html?slug=${encodeURIComponent(r.slug||'')}`;
  function card(r,large=false){const img=safeUrl(r.main_image_url);return `<article class="story-card ${large?'large':''}"><a href="${esc(link(r))}"><div class="story-img ${img?'':'no-img'}">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:'📰'}</div><div class="story-content"><div class="story-meta"><span>${esc(r.category_name||'बातमी')}</span><time>${esc(time(r.published_at||r.created_at))}</time></div><h3>${esc(r.headline||'बातमी')}</h3><p>${esc(text(r.subheadline||r.content||'',large?180:105))}</p></div></a></article>`}
  function renderWritten(rows){const box=$('#written-list');if(!box)return;if(!rows.length){box.innerHTML='<div class="loading-box">अजून लिखित बातम्या प्रकाशित झालेल्या नाहीत.</div>';return}box.innerHTML=rows.slice(0,10).map((r,i)=>card(r,i===0)).join('')}
  function renderTop(rows){const box=$('#top-stories');if(!box)return;box.innerHTML=rows.slice(0,3).map(r=>card(r)).join('')||'<div class="loading-box">प्रमुख बातम्या लोड होत आहेत…</div>'}
  function renderMini(target,rows){const box=$(target);if(!box)return;box.innerHTML=rows.slice(0,4).map(r=>{const img=safeUrl(r.main_image_url);return `<a class="mini-story" href="${esc(link(r))}">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:'<span class="mini-placeholder">•</span>'}<span><b>${esc(r.headline||'बातमी')}</b><small>${esc(time(r.published_at||r.created_at))}</small></span></a>`}).join('')||'<div class="loading-box">अजून बातम्या नाहीत.</div>'}
  function renderRanks(rows){const box=$('#trending-list');if(!box)return;box.innerHTML=rows.slice(0,5).map((r,i)=>`<li><a href="${esc(link(r))}"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(r.headline||'बातमी')}</b></a></li>`).join('')||'<li>अजून बातम्या नाहीत.</li>'}
  function renderCategory(id,rows,name){const box=$(id);if(!box)return;box.innerHTML=rows.filter(r=>(r.category_name||'').toLowerCase().includes(name)).slice(0,2).map(r=>`<a href="${esc(link(r))}">${esc(r.headline||'बातमी')} <span>→</span></a>`).join('')||'<span class="muted">लवकरच बातम्या.</span>'}
  function renderLatest(item){const box=$('#latest-content'),ep=$('#epaper-section');if(!box||!ep)return;if(!item){box.innerHTML='<div class="empty-latest">अजून प्रकाशित कंटेंट उपलब्ध नाही.</div>';return}if(item.type==='written'){const r=item.row,img=safeUrl(r.main_image_url);box.className='latest-grid latest-written-first';box.innerHTML=`<article class="lead-story"><a href="${esc(link(r))}"><div class="lead-image ${img?'':'no-img'}">${img?`<img src="${esc(img)}" alt="${esc(r.headline||'')}" fetchpriority="high">`:'📰' }<span>📝 लिखित बातमी</span></div><div class="lead-body"><div class="story-meta"><b>${esc(r.category_name||'ताजी बातमी')}</b><time>${esc(date(r.published_at||r.created_at))} • ${esc(time(r.published_at||r.created_at))}</time></div><h2>${esc(r.headline||'ताजी बातमी')}</h2><p>${esc(text(r.subheadline||r.content||'',260))}</p><strong>संपूर्ण बातमी वाचा →</strong></div></a></article>`;ep.classList.remove('latest-mounted');}else{box.className='latest-grid latest-epaper-first';box.innerHTML='';box.appendChild(ep);ep.classList.add('latest-mounted');$('#epaper-section-status').textContent='नवीनतम वृत्ते • ई-पेपर';}}
  function ticker(feed){const box=$('#ticker');if(!box)return;box.innerHTML=feed.slice(0,7).map(x=>`<span class="ticker-item"><b>${x.type==='epaper'?'ई-पेपर':esc(x.row.category_name||'बातमी')}</b> ${esc(x.type==='epaper'?`आजचा डिजिटल अंक — ${date(x.sortAt)}`:(x.row.headline||'ताजी बातमी'))}</span>`).join('')||'<span>अजून बातम्या उपलब्ध नाहीत.</span>'}
  async function init(){const t=$('#today-label');if(t)t.textContent=date(new Date());try{const rows=(await get('/news?select=id,slug,headline,subheadline,content,location,main_image_url,epaper_layout,published_at,created_at,categories(name)&status=eq.published&order=published_at.desc.nullslast,created_at.desc.nullslast&limit=200')).map(normalize).sort((a,b)=>stamp(b.published_at||b.created_at)-stamp(a.published_at||a.created_at));const written=rows.filter(r=>r.epaper_layout!=='direct-newspaper'),epapers=rows.filter(r=>r.epaper_layout==='direct-newspaper'),groups=groupEpapers(epapers),feed=unified(groups,written);renderLatest(feed[0]);renderTop(written);renderWritten(written);renderMini('#local-list',written);renderRanks(written);renderCategory('#politics-list',written,'राज');renderCategory('#sports-list',written,'क्री');renderCategory('#business-list',written,'व्यव');renderCategory('#entertainment-list',written,'मनोर');ticker(feed);if(feed[0])$('#latest-updated').textContent=`अपडेट ${time(feed[0].sortAt)}`;if(window.MetroEpaper?.loadRows)await window.MetroEpaper.loadRows(epapers);}catch(e){console.error('Lokmadat homepage error',e);$('#latest-content').innerHTML='<div class="error-box">माहिती लोड करता आली नाही. कृपया पुन्हा प्रयत्न करा.</div>';$('#written-list').innerHTML='<div class="error-box">बातम्या लोड करता आल्या नाहीत.</div>';}}
  document.addEventListener('DOMContentLoaded',()=>{init();$('#menu-btn')?.addEventListener('click',()=>$('#category-nav')?.classList.toggle('open'));});
})();
