const API_BASE=`${window.METROCITY_SUPABASE_URL}/rest/v1`;
const API_KEY=window.METROCITY_SUPABASE_KEY;
async function publicGet(path){const r=await fetch(API_BASE+path,{headers:{apikey:API_KEY,Authorization:`Bearer ${API_KEY}`},cache:'no-store'});if(!r.ok)throw new Error(`Supabase ${r.status}`);return r.json()}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const marathiDate=d=>new Intl.DateTimeFormat('mr-IN',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Kolkata'}).format(new Date(d));
const dateKey=d=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(d));const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`};
const timeLabel=d=>new Intl.DateTimeFormat('mr-IN',{hour:'numeric',minute:'2-digit',hour12:true,timeZone:'Asia/Kolkata'}).format(new Date(d));
let editions=[],selectedEdition=null,currentPage=0,zoom=1,pages=[];
const $=s=>document.querySelector(s);const setText=(id,t)=>{const e=document.getElementById(id);if(e)e.textContent=t};
function openDates(){const d=$('#date-drawer');if(d){d.classList.add('open');d.setAttribute('aria-hidden','false')}}
function closeDates(){const d=$('#date-drawer');if(d){d.classList.remove('open');d.setAttribute('aria-hidden','true')}}
function editionLabel(g){return g?.dateKey?marathiDate(`${g.dateKey}T00:00:00+05:30`):marathiDate(g.latestAt)}
function groupEditions(rows){const sorted=[...(rows||[])].sort((a,b)=>new Date(b.published_at||b.created_at)-new Date(a.published_at||a.created_at));const map=new Map();for(const row of sorted){const key=dateKey(row.published_at||row.created_at);if(!key)continue;if(!map.has(key))map.set(key,{id:`day-${key}`,dateKey:key,items:[],headline:row.headline,location:row.location,latestAt:row.published_at||row.created_at});map.get(key).items.push(row)}return [...map.values()]}
function groupPageCount(g){return g?.items?.length||0}
function renderEditionList(){const box=$('#edition-list');if(!box)return;if(!editions.length){box.innerHTML='<div class="rail-loading">अंक उपलब्ध नाहीत.</div>';return}box.innerHTML=editions.map((g,i)=>`<button class="edition-item ${selectedEdition?.id===g.id?'active':''}" data-index="${i}"><span><b>${esc(editionLabel(g))}</b><small>${groupPageCount(g)} ${groupPageCount(g)===1?'पान':'पाने'} • शेवटचे अपलोड ${timeLabel(g.latestAt)}</small></span><span class="edition-arrow">›</span></button>`).join('');box.querySelectorAll('.edition-item').forEach((b,i)=>b.addEventListener('click',()=>{selectEdition(editions[i]);closeDates()}))}
function renderRecentEditions(){const box=$('#recent-editions-list');if(!box)return;if(!editions.length){box.innerHTML='<div class="rail-loading">अजून कोणताही ई-पेपर प्रकाशित झालेला नाही.</div>';return}box.innerHTML=editions.slice(0,12).map((g,i)=>{const first=g.items[0]||{};return `<button class="recent-card" type="button" data-recent-index="${i}"><span class="recent-thumb">${first.main_image_url?`<img src="${esc(first.main_image_url)}" alt="" loading="lazy">`:'📰'}</span><span><b>${esc(editionLabel(g))}</b><small>${groupPageCount(g)} ${groupPageCount(g)===1?'पान':'पाने'} • शेवटचे अपलोड ${timeLabel(g.latestAt)}</small></span><span class="recent-arrow">›</span></button>`}).join('');box.querySelectorAll('[data-recent-index]').forEach(b=>b.addEventListener('click',()=>{selectEdition(editions[Number(b.dataset.recentIndex)]);const r=$('#epaper-section');r?.scrollIntoView({behavior:'smooth',block:'start'})}))}
function getPages(n){const urls=[];if(n.main_image_url)urls.push(n.main_image_url);if(Array.isArray(n.news_photos))for(const p of n.news_photos)if(p.image_url&&!urls.includes(p.image_url))urls.push(p.image_url);return urls}
async function enrichEdition(n){let photos=[];try{photos=await publicGet(`/news_photos?select=image_url,sort_order&news_id=eq.${encodeURIComponent(n.id)}&order=sort_order.asc`)}catch(e){console.warn(e)}return {...n,news_photos:photos||[]}}
function fitWidth(){const v=$('#paper-viewport');if(!v)return 1;const cs=getComputedStyle(v);return Math.max(1,Math.floor(v.clientWidth-(parseFloat(cs.paddingLeft)||0)-(parseFloat(cs.paddingRight)||0)))}
function fullscreenFitWidth(){const v=$('#fullscreen-stage');if(!v)return 1;const cs=getComputedStyle(v);return Math.max(1,Math.floor(v.clientWidth-(parseFloat(cs.paddingLeft)||0)-(parseFloat(cs.paddingRight)||0)))}
function applyFullscreenZoom(){const img=$('#fullscreen-image'),stage=$('#fullscreen-stage');if(!img||!stage||!$('#fullscreen-reader')?.classList.contains('open'))return;const fit=fullscreenFitWidth();const isZoom=zoom>1.001;img.style.height='auto';img.style.width=`${Math.round(fit*zoom)}px`;img.style.maxWidth='none';img.style.margin=isZoom?'0':'0 auto';img.classList.toggle('fs-zoomed',isZoom);stage.classList.toggle('zoomed-stage',isZoom);setText('fs-zoom-value',`${Math.round(zoom*100)}%`)}
function applyZoom(resetScroll=false){const img=$('#paper-image'),v=$('#paper-viewport');if(!img||!v)return;const fit=fitWidth(),isZoom=zoom>1.001;setText('zoom-value',`${Math.round(zoom*100)}%`);img.classList.toggle('zoomed',isZoom);v.classList.toggle('is-zoomed',isZoom);img.style.height='auto';img.style.transform='none';if(!isZoom){img.style.width=`${fit}px`;img.style.maxWidth=`${fit}px`;if(resetScroll){v.scrollLeft=0;v.scrollTop=0}}else{img.style.width=`${Math.round(fit*zoom)}px`;img.style.maxWidth='none'}applyFullscreenZoom()}
function resetZoom(){zoom=1;applyZoom(true)}
function updateNav(){const a=currentPage<=0,b=currentPage>=pages.length-1;['prev-page','mobile-prev','fs-prev','side-prev','fs-zoom-out'].forEach(id=>{const e=$('#'+id);if(e&&['prev-page','mobile-prev','fs-prev','side-prev'].includes(id))e.disabled=a});['next-page','mobile-next','fs-next','side-next'].forEach(id=>{const e=$('#'+id);if(e)e.disabled=b});}
function renderThumbnails(){const boxes=[$('#thumbnails'),$('#thumbnails-bottom')].filter(Boolean);if(!boxes.length)return;if(!pages.length){boxes.forEach(box=>box.innerHTML='<div class="rail-loading">पाने उपलब्ध नाहीत.</div>');return}boxes.forEach(box=>{box.innerHTML=pages.map((u,i)=>`<button class="thumb ${i===currentPage?'active':''}" type="button"><img src="${esc(u)}" alt="पान ${i+1}" loading="lazy"><span>पान ${i+1}</span></button>`).join('');box.querySelectorAll('.thumb').forEach((b,i)=>b.addEventListener('click',()=>selectPage(i)))})}
function updateFullscreenImage(){const img=$('#fullscreen-image');if(!img)return;img.src=pages[currentPage]||'';setText('fullscreen-label',`पान ${currentPage+1} / ${pages.length}`);applyFullscreenZoom()}
function selectPage(i){if(!pages.length)return;currentPage=Math.max(0,Math.min(i,pages.length-1));const img=$('#paper-image'),loading=$('#paper-loading');if(!img)return;zoom=1;applyZoom(true);loading.style.display='flex';loading.innerHTML='<div class="spinner"></div><span>ई-पेपर लोड होत आहे…</span>';img.style.visibility='hidden';img.onload=()=>{applyZoom(true);loading.style.display='none';img.style.visibility='visible'};img.onerror=()=>{loading.innerHTML='<span>हे पान लोड करता आले नाही. कृपया पुन्हा प्रयत्न करा.</span>';img.style.visibility='hidden'};img.src=pages[currentPage];setText('page-current',String(currentPage+1));setText('page-total',String(pages.length));setText('mobile-page-label',`पान ${currentPage+1}`);setText('rail-count',String(pages.length));setText('rail-count-bottom',String(pages.length));setText('below-current',String(currentPage+1));setText('below-total',String(pages.length));updateFullscreenImage();document.querySelectorAll('.thumb').forEach((x,j)=>x.classList.toggle('active',j===currentPage));updateNav();if($('#zoom-view')?.classList.contains('open')){const zi=$('#zoom-view-image'),zb=$('#zoom-view-backdrop');if(zi)zi.src=pages[currentPage];if(zb)zb.style.backgroundImage=`url("${String(pages[currentPage]).replace(/"/g,'\\"')}")`;updateZoomViewNav()}}
async function selectEdition(g){selectedEdition=g;setText('edition-title','लोकमदत • ई-पेपर');setText('edition-date',editionLabel(g));const enriched=await Promise.all(g.items.map(enrichEdition));pages=[];for(const item of enriched)pages.push(...getPages(item));currentPage=0;renderEditionList();renderThumbnails();if(!pages.length){$('#paper-image').style.display='none';$('#paper-empty').hidden=false;$('#paper-loading').style.display='none';updateNav();return}$('#paper-image').style.display='block';$('#paper-empty').hidden=true;selectPage(0)}
async function loadRows(rows){editions=groupEditions((rows||[]));renderEditionList();renderRecentEditions();if(editions.length){await selectEdition(editions[0])}else{const load=$('#paper-loading');if(load)load.style.display='none';const empty=$('#paper-empty');if(empty)empty.hidden=false;setText('edition-date','अजून कोणताही ई-पेपर प्रकाशित झालेला नाही.')}}
async function downloadCurrentPage(){if(!pages.length)return;const url=pages[currentPage];const filename=`lokmadat-${dateKey(selectedEdition?.latestAt||new Date())}-page-${currentPage+1}.jpg`;try{const r=await fetch(url,{mode:'cors',cache:'no-store'});if(!r.ok)throw 0;const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}catch{window.open(url,'_blank','noopener')}}
async function shareCurrent(){try{if(navigator.share)await navigator.share({title:`लोकमदत — ${editionLabel(selectedEdition)}`,url:location.href});else{await navigator.clipboard.writeText(location.href);alert('ई-पेपरची लिंक कॉपी झाली आहे.')}}catch{}}
function openZoomView(){if(!pages.length)return;const box=$('#zoom-view'),img=$('#zoom-view-image'),back=$('#zoom-view-backdrop');if(!box||!img)return;img.src=pages[currentPage];back.style.backgroundImage=`url("${String(pages[currentPage]).replace(/"/g,'\\"')}")`;setText('zoom-view-label',`पान ${currentPage+1} / ${pages.length}`);box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';updateZoomViewNav()}
function closeZoomView(){const box=$('#zoom-view');if(!box)return;box.classList.remove('open');box.setAttribute('aria-hidden','true');$('#zoom-view-image')?.removeAttribute('src');const back=$('#zoom-view-backdrop');if(back)back.style.backgroundImage='none';if(!$('#fullscreen-reader')?.classList.contains('open'))document.body.style.overflow=''}
function updateZoomViewNav(){const a=$('#zoom-view-prev'),b=$('#zoom-view-next');if(a)a.disabled=currentPage<=0;if(b)b.disabled=currentPage>=pages.length-1;setText('zoom-view-label',`पान ${currentPage+1} / ${pages.length}`)}
function changeZoomViewPage(delta){const next=Math.max(0,Math.min(currentPage+delta,pages.length-1));if(next===currentPage)return;selectPage(next);requestAnimationFrame(()=>{$('#zoom-view-stage')?.scrollTo({top:0,left:0,behavior:'auto'});updateZoomViewNav()})}
async function openFullscreen(){if(!pages.length)return;const f=$('#fullscreen-reader');f.classList.add('open');f.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';zoom=1;const stage=$('#fullscreen-stage');if(stage){stage.scrollLeft=0;stage.scrollTop=0}updateFullscreenImage();requestAnimationFrame(()=>applyFullscreenZoom());try{if(f.requestFullscreen)await f.requestFullscreen()}catch{}}
async function closeFullscreen(){const f=$('#fullscreen-reader');f.classList.remove('open');f.setAttribute('aria-hidden','true');$('#fullscreen-image')?.removeAttribute('src');document.body.style.overflow='';try{if(document.fullscreenElement)await document.exitFullscreen()}catch{}}
function changePage(delta){const next=Math.max(0,Math.min(currentPage+delta,pages.length-1));if(next!==currentPage){const y=window.scrollY;selectPage(next);requestAnimationFrame(()=>{if(!$('#fullscreen-reader')?.classList.contains('open'))window.scrollTo({top:y,left:0,behavior:'auto'})})}}
function bindReader(){const bind=(id,fn)=>document.getElementById(id)?.addEventListener('click',fn);const zoomIn=()=>{zoom=Math.min(3,+(zoom+.25).toFixed(2));applyZoom()};const zoomOut=()=>{zoom=Math.max(1,+(zoom-.25).toFixed(2));applyZoom()};const fsZoomIn=()=>{zoom=Math.min(4,+(zoom+.25).toFixed(2));applyZoom();applyFullscreenZoom()};const fsZoomOut=()=>{zoom=Math.max(1,+(zoom-.25).toFixed(2));applyZoom();applyFullscreenZoom()};const fsFit=()=>{zoom=1;applyZoom(true);applyFullscreenZoom()};bind('date-open',openDates);bind('date-close',closeDates);bind('share-btn',shareCurrent);bind('download-btn',downloadCurrentPage);bind('prev-page',()=>changePage(-1));bind('next-page',()=>changePage(1));bind('side-prev',()=>changePage(-1));bind('side-next',()=>changePage(1));bind('below-prev',()=>changePage(-1));bind('below-next',()=>changePage(1));bind('zoom-in',zoomIn);bind('zoom-out',zoomOut);bind('fit-btn',resetZoom);bind('zoom-view-btn',openZoomView);bind('zoom-view-close',closeZoomView);bind('zoom-view-backdrop',closeZoomView);bind('zoom-view-prev',()=>changeZoomViewPage(-1));bind('zoom-view-next',()=>changeZoomViewPage(1));bind('zoom-view-download',downloadCurrentPage);bind('fullscreen-btn',openFullscreen);bind('fullscreen-close',closeFullscreen);bind('fs-prev',()=>changePage(-1));bind('fs-next',()=>changePage(1));bind('fs-download',downloadCurrentPage);bind('fs-zoom-in',fsZoomIn);bind('fs-zoom-out',fsZoomOut);bind('fs-fit',fsFit);$('#date-drawer')?.addEventListener('click',e=>{if(e.target.id==='date-drawer')closeDates()});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&$('#fullscreen-reader')?.classList.contains('open'))closeFullscreen()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDates();closeFullscreen();closeZoomView()}if(e.key==='ArrowLeft')changePage(-1);if(e.key==='ArrowRight')changePage(1);if(e.key==='+'||e.key==='='){if($('#fullscreen-reader')?.classList.contains('open'))fsZoomIn();else zoomIn()}if(e.key==='-'){if($('#fullscreen-reader')?.classList.contains('open'))fsZoomOut();else zoomOut()}});const view=$('#paper-viewport');let swipe=null;view?.addEventListener('touchstart',e=>{if(zoom>1.001||e.touches.length!==1)return;swipe={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});view?.addEventListener('touchend',e=>{if(!swipe||e.changedTouches.length!==1){swipe=null;return}const dx=e.changedTouches[0].clientX-swipe.x,dy=e.changedTouches[0].clientY-swipe.y;swipe=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.35)changePage(dx<0?1:-1)},{passive:true});
const fsStage=$('#fullscreen-stage');
let pinchStartDistance=0,pinchStartZoom=1,pinchCenterX=0,pinchCenterY=0;
const touchDistance=(a,b)=>Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);
fsStage?.addEventListener('touchstart',e=>{
  if(e.touches.length===2){
    pinchStartDistance=touchDistance(e.touches[0],e.touches[1]);
    pinchStartZoom=zoom;
    pinchCenterX=(e.touches[0].clientX+e.touches[1].clientX)/2;
    pinchCenterY=(e.touches[0].clientY+e.touches[1].clientY)/2;
  }else{
    pinchStartDistance=0;
  }
},{passive:true});
fsStage?.addEventListener('touchmove',e=>{
  if(e.touches.length===2&&pinchStartDistance>0){
    e.preventDefault();
    const ratio=touchDistance(e.touches[0],e.touches[1])/pinchStartDistance;
    zoom=Math.max(1,Math.min(4,+(pinchStartZoom*ratio).toFixed(2)));
    applyFullscreenZoom();
  }
},{passive:false});
fsStage?.addEventListener('touchend',e=>{if(e.touches.length<2)pinchStartDistance=0},{passive:true});

window.addEventListener('resize',()=>{if(zoom<=1.001)applyZoom(false);if($('#fullscreen-reader')?.classList.contains('open'))applyFullscreenZoom()});window.addEventListener('orientationchange',()=>setTimeout(()=>{if(zoom<=1.001)applyZoom(true);if($('#fullscreen-reader')?.classList.contains('open'))applyFullscreenZoom()},80))}
async function loadSingle(){const params=new URLSearchParams(location.search);const requestedDate=params.get('date');const requestedPage=Math.max(1,parseInt(params.get('page')||'1',10)||1);try{const rows=await publicGet('/news?select=id,slug,headline,location,main_image_url,epaper_layout,published_at,created_at&status=eq.published&order=published_at.desc.nullslast,created_at.desc.nullslast&limit=200');editions=groupEditions((rows||[]).filter(n=>n.epaper_layout==='direct-newspaper'));renderEditionList();renderRecentEditions();const target=requestedDate?editions.find(g=>g.dateKey===requestedDate):editions[0];if(!target){setText('edition-title','ई-पेपर उपलब्ध नाही');setText('edition-date',requestedDate?'त्या तारखेचा अंक सापडला नाही.':'अजून कोणताही ई-पेपर प्रकाशित झालेला नाही.');$('#paper-loading').style.display='none';$('#paper-empty').hidden=false;return}await selectEdition(target);if(requestedPage>1&&requestedPage<=pages.length)selectPage(requestedPage-1)}catch(e){console.error(e);$('#paper-loading').innerHTML='<span>ई-पेपर लोड करताना अडचण आली. कृपया पुन्हा प्रयत्न करा.</span>'}}
window.MetroEpaper={loadRows,selectEdition,changePage,openZoomView,openFullscreen};
document.addEventListener('DOMContentLoaded',()=>{bindReader();if(document.body.classList.contains('single-paper'))loadSingle();else if(!document.body.classList.contains('home-reader')){(async()=>{try{const rows=await publicGet('/news?select=id,slug,headline,location,main_image_url,epaper_layout,published_at,created_at&status=eq.published&order=published_at.desc.nullslast,created_at.desc.nullslast&limit=200');await loadRows((rows||[]).filter(n=>n.epaper_layout==='direct-newspaper'))}catch(e){console.error(e)}})()}});
