const { createClient } = window.supabase;
const db = createClient(window.METROCITY_SUPABASE_URL, window.METROCITY_SUPABASE_KEY);
const mrWeekdays=['रविवार','सोमवार','मंगळवार','बुधवार','गुरुवार','शुक्रवार','शनिवार'];
const mrMonths=['जानेवारी','फेब्रुवारी','मार्च','एप्रिल','मे','जून','जुलै','ऑगस्ट','सप्टेंबर','ऑक्टोबर','नोव्हेंबर','डिसेंबर'];
function devDigits(v){return String(v).replace(/\d/g,d=>'०१२३४५६७८९'[d]);}
function marathiDate(date=new Date()){return `${mrWeekdays[date.getDay()]}, ${devDigits(date.getDate())} ${mrMonths[date.getMonth()]} ${devDigits(date.getFullYear())}`;}
function setDates(){document.querySelectorAll('[data-current-date]').forEach(el=>el.textContent=marathiDate());}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function nl2p(v=''){return v.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>`<p>${esc(x)}</p>`).join('');}
function copyLink(){navigator.clipboard?.writeText(location.href).then(()=>alert('लिंक कॉपी झाली आहे.')).catch(()=>prompt('ही लिंक कॉपी करा:',location.href));}
function shareNews(){if(navigator.share){navigator.share({title:document.title,url:location.href}).catch(()=>{});}else copyLink();}
function toggleSearch(){document.querySelector('.searchbox')?.classList.toggle('show');document.querySelector('.searchbox input')?.focus();}
function relativeTime(iso){if(!iso)return '';const m=Math.max(0,Math.floor((Date.now()-new Date(iso))/60000));if(m<1)return 'आत्ताच';if(m<60)return `${devDigits(m)} मिनिटांपूर्वी`;const h=Math.floor(m/60);if(h<24)return `${devDigits(h)} तासांपूर्वी`;const d=Math.floor(h/24);return `${devDigits(d)} दिवसांपूर्वी`;}
function img(url,cls=''){return url?`<img class="${cls}" src="${esc(url)}" alt="" loading="lazy">`:`<div class="photo ${cls}">छायाचित्र</div>`;}
async function loadHome(){
  const {data,error}=await db.from('news').select('id,slug,headline,subheadline,location,main_image_url,epaper_layout,published_at,categories(name,slug)').eq('status','published').order('published_at',{ascending:false}).limit(12);
  const root=document.querySelector('#live-news'); if(!root)return;
  if(error){root.innerHTML='<p class="error">बातम्या लोड करता आल्या नाहीत. कृपया पुन्हा प्रयत्न करा.</p>';return;}
  if(!data?.length){root.innerHTML='<div class="empty"><h3>अजून बातम्या प्रकाशित झालेल्या नाहीत.</h3><p>प्रतिनिधी पॅनेलमधून पहिली बातमी प्रकाशित करा.</p></div>';return;}
  const [hero,...rest]=data;
  const heroEl=document.querySelector('#live-hero');
  if(heroEl){heroEl.innerHTML=`<article class="hero-paper" onclick="location.href='article.html?slug=${encodeURIComponent(hero.slug)}'"><div class="paperhead"><b>मेट्रोसिटी पोस्ट</b><span>विशेष आवृत्ती • ${marathiDate(new Date(hero.published_at))}</span></div><hr><small>${esc(hero.categories?.name||'बातमी')}</small><h2>${esc(hero.headline)}</h2><p class="lead">${esc(hero.subheadline||'मेट्रोसिटी पोस्टचे सविस्तर वृत्तांकन.')}</p><div class="hero-paper-body">${img(hero.main_image_url,'news-photo')}<div class="columns">${nl2p(hero.subheadline||hero.headline)}</div></div><div class="paper-foot">${esc(hero.location||'महाराष्ट्र')} <b>बातमी वाचा →</b></div></article>`;}
  root.innerHTML=rest.map(n=>`<article class="news-card" onclick="location.href='article.html?slug=${encodeURIComponent(n.slug)}'"><div>${img(n.main_image_url,'card-photo')}</div><small>${esc(n.categories?.name||'बातमी')}</small><h3>${esc(n.headline)}</h3><p>${esc(n.subheadline||'')}</p><time>${relativeTime(n.published_at)}</time></article>`).join('');
  const side=document.querySelector('#live-side'); if(side)side.innerHTML=rest.slice(0,4).map(n=>`<article onclick="location.href='article.html?slug=${encodeURIComponent(n.slug)}'"><small>${esc(n.categories?.name||'बातमी')}</small><h3>${esc(n.headline)}</h3><time>${relativeTime(n.published_at)}</time></article>`).join('');
}
async function searchNews(q){const box=document.querySelector('#search-results');if(!box)return; if(!q.trim()){box.innerHTML='';return;} const term=q.trim(); const {data,error}=await db.from('news').select('slug,headline,subheadline,published_at,categories(name)').eq('status','published').or(`headline.ilike.%${term}%,subheadline.ilike.%${term}%`).order('published_at',{ascending:false}).limit(20); if(error){box.innerHTML='<p class="error">शोध करताना अडचण आली.</p>';return;} box.innerHTML=data.length?data.map(n=>`<a class="search-result" href="article.html?slug=${encodeURIComponent(n.slug)}"><small>${esc(n.categories?.name||'बातमी')}</small><b>${esc(n.headline)}</b><span>${relativeTime(n.published_at)}</span></a>`).join(''):'<p class="empty">या शोधासाठी बातमी सापडली नाही.</p>';}
async function loadArticle(){const params=new URLSearchParams(location.search);const slug=params.get('slug');if(!slug)return;const {data,error}=await db.from('news').select('*,categories(name,slug)').eq('slug',slug).maybeSingle();if(error||!data){document.querySelector('#article-content').innerHTML='<section class="normal"><h2>बातमी सापडली नाही</h2><p>ही बातमी उपलब्ध नाही किंवा हटवली गेली आहे.</p></section>';return;} document.title=`${data.headline} | मेट्रोसिटी पोस्ट`;document.querySelector('meta[name="description"]')?.setAttribute('content',data.seo_description||data.subheadline||data.headline); const photos=await db.from('news_photos').select('*').eq('news_id',data.id).order('sort_order'); const photoUrls=[data.main_image_url,...(photos.data||[]).map(p=>p.image_url)].filter(Boolean); const photoHtml=photoUrls.length?photoUrls.map((u,i)=>img(u,i?'article-gallery-img':'articlephoto')).join(''):'<div class="photo articlephoto">मुख्य छायाचित्र</div>';
  const paper=document.querySelector('#paper'); if(paper){let layout=data.epaper_layout||'auto'; if(layout==='auto') layout=data.main_image_url?'photo-left':'no-photo'; paper.className='epaper layout-'+layout; paper.innerHTML=`<div class="paperhead"><b>मेट्रोसिटी पोस्ट</b><span>${marathiDate(new Date(data.published_at||data.created_at))} • ${esc(data.categories?.name||'विशेष')}</span></div><hr><small>${esc(data.location||'महाराष्ट्र')} • ${esc(data.categories?.name||'बातमी')}</small><h1>${esc(data.headline)}</h1><p class="dek">${esc(data.subheadline||'')}</p><div class="newspaperbody">${data.main_image_url?img(data.main_image_url,'news-photo big'):''}<div class="columns">${nl2p(data.content).replace(/<p>/g,'<p>')}</div></div><div class="paper-foot">प्रतिनिधी : ${'मेट्रोसिटी पोस्ट'} <span>${marathiDate(new Date(data.published_at||data.created_at))}</span></div>`;}
  const normal=document.querySelector('#article-normal'); if(normal)normal.innerHTML=`<small>सविस्तर बातमी</small><h2>${esc(data.headline)}</h2><div class="meta">${'मेट्रोसिटी पोस्ट'} • ${marathiDate(new Date(data.published_at||data.created_at))}${data.location?' • '+esc(data.location):''}</div><div class="article-gallery">${photoHtml}</div><div class="article-text">${nl2p(data.content)}</div>`;
  const rel=document.querySelector('#related'); if(rel){const {data:r}=await db.from('news').select('slug,headline,subheadline,published_at,categories(name)').eq('status','published').neq('id',data.id).eq('category_id',data.category_id).order('published_at',{ascending:false}).limit(3);rel.innerHTML=(r||[]).map(n=>`<article><small>${esc(n.categories?.name||'बातमी')}</small><h3><a href="article.html?slug=${encodeURIComponent(n.slug)}">${esc(n.headline)}</a></h3></article>`).join('');}
  db.rpc('increment_news_views',{news_id:data.id}).catch(()=>{});
}
function wireSearch(){const input=document.querySelector('.searchbox input');if(input){let t;input.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>searchNews(input.value),300);});input.addEventListener('keydown',e=>{if(e.key==='Enter')searchNews(input.value);});}}
document.addEventListener('DOMContentLoaded',()=>{setDates();wireSearch();loadHome();loadArticle();});
